// DATA SECTION

var encounterTables = {
	"basetable": {
		"1": [25, 50, 75, 100],
		"2": [50, 100, 150, 200],
		"3": [75, 150, 225, 400],
		"4": [125, 250, 375, 500],
		"5": [250, 500, 750, 1100],
		"6": [300, 600, 900, 1400],
		"7": [350, 750, 1100, 1700],
		"8": [450, 900, 1400, 2100],
		"9": [550, 1100, 1600, 2400],
		"10": [600, 1200, 1900, 2800],
		"11": [800, 1600, 2400, 3600],
		"12": [1000, 2000, 3000, 4500],
		"13": [1100, 2200, 3400, 5100],
		"14": [1250, 2500, 3800, 5700],
		"15": [1400, 2800, 4300, 6400],
		"16": [1600, 3200, 4800, 7200],
		"17": [2000, 3900, 5900, 8800],
		"18": [2100, 4200, 6300, 9500],
		"19": [2400, 4900, 7300, 1090],
		"20": [2800, 5700, 8500, 12700],
	},

	"maxexp": {
		"1": [1, 25, 50, 75, 50],
		"2": [1.5, 33, 67, 100, 133],
	}
};
var modArray = ["N/A", -5, -4, -4, -3, -3, -2, -2, -1, -1, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10];

var challengeArray = {
	"0": ["10", "2"],
	"1/8": ["25", "2"],
	"1/4": ["50", "2"],
	"1/2": ["100", "2"],
	"1": ["200", "2"],
	"2": ["450", "2"],
	"3": ["700", "2"],
	"4": ["1,100", "2"],
	"5": ["1,800", "3"],
	"6": ["2,300", "3"],
	"7": ["2,900", "3"],
	"8": ["3,900", "3"],
	"9": ["5,000", "4"],
	"10": ["5,900", "4"],
	"11": ["7,200", "4"],
	"12": ["8,400", "4"],
	"13": ["10,000", "5"],
	"14": ["11,500", "5"],
	"15": ["13,000", "5"],
	"16": ["15,000", "5"],
	"17": ["18,000", "6"],
	"18": ["20,000", "6"],
	"19": ["22,000", "6"],
	"20": ["25,000", "6"],
	"21": ["33,000", "7"],
	"22": ["41,000", "7"],
	"23": ["50,000", "8"],
	"24": ["62,000", "8"],
	"25": ["75,000", "8"],
	"26": ["90,000", "8"],
	"27": ["105,000", "8"],
	"28": ["120,000", "8"],
	"29": ["135,000", "9"],
	"30": ["155,000", "9"],
};

var CoS_Dialog = {
	"Baba Lysaga": -1,
	"Baba Lysaga's Creeping Hut": -1,
	"Barovian Witch": -1,
	"Broom of Animated Attack": -1,
	"Ezmerelda d'Avenir": -1,
	"Guardian Portrait": -1,
	"Izek Strazni": -1,
	"Madam Eva": -1,
	"Mongrelfolk": -1,
	"Phantom Warrior": -1,
	"Pidlwick II": -1,
	"Rahadin": -1,
	"Rictavio": -1,
	"Strahd's Animated Armor": -1,
	"Strahd von Zarovich": -1,
	"Strahd Zombie": -1,
	"Tree Blight": -1,
	"Vladimir Horngaard": -1,
	"Wereraven": -1,
};
var EE_Dialog = {
	"Aerisi Kalinoth": -1,
	"Air Elemental Myrmidon": -1,
	"Bastian Thermandar": -1,
	"Black Earth Guard": -1,
	"Black Earth Priest": -1,
	"Burrowshark": -1,
	"Crushing Wave Priest": -1,
	"Crushing Wave Reaver": -1,
	"Dark Tide Knight": -1,
	"Drannin Splithelm": -1,
	"Earth Elemental Myrmidon": -1,
	"Elizar Dryflagon": -1,
	"Eternal Flame Guardian": -1,
	"Eternal Flame Priest": -1,
	"Fathomer": -1,
	"Feathergale Knight": -1,
	"Fire Elemental Myrmidon": -1,
	"Flamewrath": -1,
	"Gar Shatterkeel": -1,
	"Ghald": -1,
	"Hellenrae": -1,
	"Howling Hatred Initiate": -1,
	"Howling Hatred Priest": -1,
	"Hurricane": -1,
	"Imix": -1,
	"Marlos Urnrayle": -1,
	"Miraj Vizann": -1,
	"Ogremoch": -1,
	"Olhydra": -1,
	"One-Eyed Shiver": -1,
	"Oreioth": -1,
	"Razerblast": -1,
	"Sacred Stone Monk": -1,
	"Shoalar Quanderil": -1,
	"Skyweaver": -1,
	"Stonemelder": -1,
	"Thurl Merosska": -1,
	"Vanifer": -1,
	"Water Elemental Myrmidon": -1,
	"Wiggan Nettlebee": -1,
	"Windharrow": -1,
	"Yan-C-Bin": -1,
};
var MM_Dialog = {
	"Aarakocra": -1,
	"Aboleth": -1,
	"Abominable Yeti": -1,
	"Acolyte": -1,
	"Adult Black Dragon": -1,
	"Adult Blue Dracolich": -1,
	"Adult Blue Dragon": -1,
	"Adult Brass Dragon": -1,
	"Adult Bronze Dragon": -1,
	"Adult Copper Dragon": -1,
	"Adult Gold Dragon": -1,
	"Adult Green Dragon": -1,
	"Adult Red Dragon": -1,
	"Adult Silver Dragon": -1,
	"Adult White Dragon": -1,
	"Air Elemental": -1,
	"Allosaurus": -1,
	"Ancient Black Dragon": -1,
	"Ancient Blue Dragon": -1,
	"Ancient Brass Dragon": -1,
	"Ancient Bronze Dragon": -1,
	"Ancient Copper Dragon": -1,
	"Ancient Gold Dragon": -1,
	"Ancient Green Dragon": -1,
	"Ancient Red Dragon": -1,
	"Ancient Silver Dragon": -1,
	"Ancient White Dragon": -1,
	"Androsphinx": -1,
	"Animated Armor": -1,
	"Ankheg": -1,
	"Ankylosaurus": -1,
	"Ape": -1,
	"Arcanaloth": -1,
	"Archmage": -1,
	"Assassin": -1,
	"Awakened Shrub": -1,
	"Awakened Tree": -1,
	"Axe Beak": -1,
	"Azer": -1,
	"Baboon": -1,
	"Badger": -1,
	"Balor": -1,
	"Bandit": -1,
	"Bandit Captain": -1,
	"Banshee": -1,
	"Barbed Devil": -1,
	"Barlgura": -1,
	"Basilisk": -1,
	"Bat": -1,
	"Bearded Devil": -1,
	"Behir": -1,
	"Beholder": -1,
	"Beholder Zombie": -1,
	"Berserker": -1,
	"Black Bear": -1,
	"Black Dragon Wyrmling": -1,
	"Black Pudding": -1,
	"Blink Dog": -1,
	"Blood Hawk": -1,
	"Blue Dragon Wyrmling": -1,
	"Blue Slaad": -1,
	"Boar": -1,
	"Bone Devil": -1,
	"Bone Devil Polearm": -1,
	"Bone Naga (Guardian)": -1,
	"Bone Naga (Spirit)": -1,
	"Brass Dragon Wyrmling": -1,
	"Bronze Dragon Wyrmling": -1,
	"Brown Bear": -1,
	"Bugbear": -1,
	"Bugbear Chief": -1,
	"Bulette": -1,
	"Bullywug": -1,
	"Cambion": -1,
	"Camel": -1,
	"Carrion Crawler": -1,
	"Cat": -1,
	"Cave Bear": -1,
	"Centaur": -1,
	"Chain Devil": -1,
	"Chasme": -1,
	"Chimera": -1,
	"Chuul": -1,
	"Clay Golem": -1,
	"Cloaker": -1,
	"Cloud Giant": -1,
	"Cockatrice": -1,
	"Commoner": -1,
	"Constrictor Snake": -1,
	"Copper Dragon Wyrmling": -1,
	"Couatl": -1,
	"Crab": -1,
	"Crawling Claw": -1,
	"Crocodile": -1,
	"Cult Fanatic": -1,
	"Cultist": -1,
	"Cyclops": -1,
	"Dao": -1,
	"Darkmantle": -1,
	"Death Dog": -1,
	"Death Knight": -1,
	"Death Slaad": -1,
	"Death Tyrant": -1,
	"Deep Gnome (Svirfneblin)": -1,
	"Deer": -1,
	"Demilich": -1,
	"Deva": -1,
	"Dire Wolf": -1,
	"Displacer Beast": -1,
	"Djinni": -1,
	"Doppelganger": -1,
	"Draft Horse": -1,
	"Dragon Turtle": -1,
	"Dretch": -1,
	"Drider": -1,
	"Drider Spellcaster": -1,
	"Drow": -1,
	"Drow Elite Warrior": -1,
	"Drow Mage": -1,
	"Drow Priestess of Lolth": -1,
	"Druid": -1,
	"Dryad": -1,
	"Duergar": -1,
	"Duodrone": -1,
	"Dust Mephit": -1,
	"Eagle": -1,
	"Earth Elemental": -1,
	"Efreeti": -1,
	"Elephant": -1,
	"Elk": -1,
	"Empyrean": -1,
	"Erinyes": -1,
	"Ettercap": -1,
	"Ettin": -1,
	"Faerie Dragon (Blue)": -1,
	"Faerie Dragon (Green)": -1,
	"Faerie Dragon (Indigo)": -1,
	"Faerie Dragon (Orange)": -1,
	"Faerie Dragon (Red)": -1,
	"Faerie Dragon (Violet)": -1,
	"Faerie Dragon (Yellow)": -1,
	"Fire Elemental": -1,
	"Fire Giant": -1,
	"Fire Snake": -1,
	"Flameskull": -1,
	"Flesh Golem": -1,
	"Flumph": -1,
	"Flying Snake": -1,
	"Flying Sword": -1,
	"Fomorian": -1,
	"Frog": -1,
	"Frost Giant": -1,
	"Galeb Duhr": -1,
	"Gargoyle": -1,
	"Gas Spore": -1,
	"Gelatinous Cube": -1,
	"Ghast": -1,
	"Ghost": -1,
	"Ghoul": -1,
	"Giant Ape": -1,
	"Giant Badger": -1,
	"Giant Bat": -1,
	"Giant Boar": -1,
	"Giant Centipede": -1,
	"Giant Constrictor Snake": -1,
	"Giant Crab": -1,
	"Giant Crocodile": -1,
	"Giant Eagle": -1,
	"Giant Elk": -1,
	"Giant Fire Beetle": -1,
	"Giant Fly": -1,
	"Giant Frog": -1,
	"Giant Goat": -1,
	"Giant Hyena": -1,
	"Giant Lizard": -1,
	"Giant Octopus": -1,
	"Giant Owl": -1,
	"Giant Poisonous Snake": -1,
	"Giant Rat": -1,
	"Giant Rat (diseased)": -1,
	"Giant Scorpion": -1,
	"Giant Sea Horse": -1,
	"Giant Shark": -1,
	"Giant Spider": -1,
	"Giant Toad": -1,
	"Giant Vulture": -1,
	"Giant Wasp": -1,
	"Giant Weasel": -1,
	"Giant Wolf Spider": -1,
	"Gibbering Mouther": -1,
	"Githyanki Knight": -1,
	"Githyanki Warrior": -1,
	"Githzerai Monk": -1,
	"Githzerai Zerth": -1,
	"Glabrezu": -1,
	"Gladiator": -1,
	"Gnoll": -1,
	"Gnoll Fang of Yeenoghu": -1,
	"Gnoll Pack Lord": -1,
	"Goat": -1,
	"Goblin": -1,
	"Goblin Boss": -1,
	"Gold Dragon Wyrmling": -1,
	"Gorgon": -1,
	"Goristro": -1,
	"Gray Ooze": -1,
	"Gray Ooze (Psychic)": -1,
	"Gray Slaad": -1,
	"Green Dragon Wyrmling": -1,
	"Green Hag": -1,
	"Green Slaad": -1,
	"Grell": -1,
	"Grick": -1,
	"Grick Alpha": -1,
	"Griffon": -1,
	"Grimlock": -1,
	"Guard": -1,
	"Guardian Naga": -1,
	"Gynosphinx": -1,
	"Half-Ogre (Ogrillon)": -1,
	"Half-Red Dragon Veteran": -1,
	"Harpy": -1,
	"Hawk": -1,
	"Hell Hound": -1,
	"Helmed Horror": -1,
	"Hezrou": -1,
	"Hill Giant": -1,
	"Hippogriff": -1,
	"Hobgoblin": -1,
	"Hobgoblin Captain": -1,
	"Hobgoblin Warlord": -1,
	"Homunculus": -1,
	"Hook Horror": -1,
	"Horned Devil": -1,
	"Hunter Shark": -1,
	"Hydra": -1,
	"Hyena": -1,
	"Ice Devil": -1,
	"Ice Devil Spear": -1,
	"Ice Mephit": -1,
	"Imp": -1,
	"Intellect Devourer": -1,
	"Invisible Stalker": -1,
	"Iron Golem": -1,
	"Iymrith, Ancient Blue Dragon": -1,
	"Jackal": -1,
	"Jackalwere": -1,
	"Kenku": -1,
	"Killer Whale": -1,
	"Knight": -1,
	"Kobold": -1,
	"Kraken": -1,
	"Kuo-Toa": -1,
	"Kuo-Toa Archpriest": -1,
	"Kuo-Toa Monitor": -1,
	"Kuo-Toa Whip": -1,
	"Lamia": -1,
	"Lemure": -1,
	"Lich": -1,
	"Lion": -1,
	"Lizard": -1,
	"Lizard King/Queen": -1,
	"Lizardfolk": -1,
	"Lizardfolk Shaman": -1,
	"Mage": -1,
	"Magma Mephit": -1,
	"Magmin": -1,
	"Mammoth": -1,
	"Manes": -1,
	"Manticore": -1,
	"Marid": -1,
	"Marilith": -1,
	"Mastiff": -1,
	"Medusa": -1,
	"Merfolk": -1,
	"Merrow": -1,
	"Mezzoloth": -1,
	"Mimic": -1,
	"Mind Flayer": -1,
	"Mind Flayer Arcanist": -1,
	"Minotaur": -1,
	"Minotaur Skeleton": -1,
	"Monodrone": -1,
	"Mud Mephit": -1,
	"Mule": -1,
	"Mummy": -1,
	"Mummy Lord": -1,
	"Myconid Adult": -1,
	"Myconid Sovereign": -1,
	"Myconid Sprout": -1,
	"Nalfeshnee": -1,
	"Needle Blight": -1,
	"Night Hag": -1,
	"Nightmare": -1,
	"Noble": -1,
	"Nothic": -1,
	"Nycaloth": -1,
	"Ochre Jelly": -1,
	"Octopus": -1,
	"Ogre": -1,
	"Ogre Zombie": -1,
	"Oni": -1,
	"Orc": -1,
	"Orc Eye of Gruumsh": -1,
	"Orc War Chief": -1,
	"Orog": -1,
	"Otyugh": -1,
	"Owl": -1,
	"Owlbear": -1,
	"Panther": -1,
	"Pegasus": -1,
	"Pentadrone": -1,
	"Peryton": -1,
	"Phase Spider": -1,
	"Piercer": -1,
	"Pit Fiend": -1,
	"Pixie": -1,
	"Planetar": -1,
	"Plesiosaurus": -1,
	"Poisonous Snake": -1,
	"Polar Bear": -1,
	"Poltergeist": -1,
	"Pony": -1,
	"Priest": -1,
	"Pseudodragon": -1,
	"Pteranodon": -1,
	"Purple Worm": -1,
	"Quadrone": -1,
	"Quaggoth": -1,
	"Quaggoth Spore Servant": -1,
	"Quaggoth Thonot": -1,
	"Quasit": -1,
	"Quipper": -1,
	"Rakshasa": -1,
	"Rat": -1,
	"Raven": -1,
	"Red Dragon Wyrmling": -1,
	"Red Slaad": -1,
	"Reef Shark": -1,
	"Remorhaz": -1,
	"Revenant": -1,
	"Rhinoceros": -1,
	"Riding Horse": -1,
	"Roc": -1,
	"Roper": -1,
	"Rug Of Smothering": -1,
	"Rust Monster": -1,
	"Saber-Toothed Tiger": -1,
	"Sahuagin": -1,
	"Sahuagin Baron": -1,
	"Sahuagin Priestess": -1,
	"Salamander": -1,
	"Satyr": -1,
	"Scarecrow": -1,
	"Scorpion": -1,
	"Scout": -1,
	"Sea Hag": -1,
	"Sea Horse": -1,
	"Shadow": -1,
	"Shadow Demon": -1,
	"Shambling Mound": -1,
	"Shield Guardian": -1,
	"Shrieker": -1,
	"Silver Dragon Wyrmling": -1,
	"Skeleton": -1,
	"Slaad Tadpole": -1,
	"Smoke Mephit": -1,
	"Solar": -1,
	"Spectator": -1,
	"Specter": -1,
	"Spider": -1,
	"Spined Devil": -1,
	"Spirit Naga": -1,
	"Sprite": -1,
	"Spy": -1,
	"Steam Mephit": -1,
	"Stirge": -1,
	"Stone Giant": -1,
	"Stone Golem": -1,
	"Storm Giant": -1,
	"Succubus/Incubus": -1,
	"Swarm Of Bats": -1,
	"Swarm Of Beetles": -1,
	"Swarm of Centipedes": -1,
	"Swarm of Insects": -1,
	"Swarm of Poisonous Snakes": -1,
	"Swarm of Quippers": -1,
	"Swarm of Rats": -1,
	"Swarm of Ravens": -1,
	"Swarm of Spiders": -1,
	"Swarm of Wasps": -1,
	"Tarrasque": -1,
	"Thri-kreen": -1,
	"Thri-kreen (Psionic)": -1,
	"Thug": -1,
	"Tiger": -1,
	"Treant": -1,
	"Tribal Warrior": -1,
	"Triceratops": -1,
	"Tridrone": -1,
	"Troglodyte": -1,
	"Troll": -1,
	"Twig Blight": -1,
	"Tyrannosaurus Rex": -1,
	"Ultroloth": -1,
	"Umber Hulk": -1,
	"Unicorn": -1,
	"Vampire": -1,
	"Vampire Spawn": -1,
	"Vampire Spellcaster": -1,
	"Vampire Warrior": -1,
	"Veteran": -1,
	"Vine Blight": -1,
	"Violet Fungus": -1,
	"Vrock": -1,
	"Vulture": -1,
	"Warhorse": -1,
	"Warhorse Skeleton": -1,
	"Water Elemental": -1,
	"Water Weird": -1,
	"Weasel": -1,
	"Werebear": -1,
	"Wereboar": -1,
	"Wererat": -1,
	"Weretiger": -1,
	"Werewolf": -1,
	"White Dragon Wyrmling": -1,
	"Wight": -1,
	"Will-o'-Wisp": -1,
	"Winged Kobold": -1,
	"Winter Wolf": -1,
	"Wolf": -1,
	"Worg": -1,
	"Wraith": -1,
	"Wyvern": -1,
	"Xorn": -1,
	"Yeti": -1,
	"Yochlol": -1,
	"Young Black Dragon": -1,
	"Young Blue Dragon": -1,
	"Young Brass Dragon": -1,
	"Young Bronze Dragon": -1,
	"Young Copper Dragon": -1,
	"Young Gold Dragon": -1,
	"Young Green Dragon": -1,
	"Young Red Dragon": -1,
	"Young Red Shadow Dragon": -1,
	"Young Remorhaz": -1,
	"Young Silver Dragon": -1,
	"Young White Dragon": -1,
	"Yuan-ti Abomination": -1,
	"Yuan-ti Malison Type 1": -1,
	"Yuan-ti Malison Type 2": -1,
	"Yuan-ti Malison Type 3": -1,
	"Yuan-ti Pureblood": -1,
	"Zombie": -1,
};
var MToF_Dialog = {
	"Abyssal Wretch": -1,
	"Adult Kruthik": -1,
	"Adult Oblex": -1,
	"Air Elemental Myrmidon": -1,
	"Alkilith": -1,
	"Allip": -1,
	"Amnizu": -1,
	"Armanite": -1,
	"Astral Dreadnought": -1,
	"Autumn Eladrin": -1,
	"Bael": -1,
	"Balhannoth": -1,
	"Baphomet": -1,
	"Berbalang": -1,
	"Black Abishai": -1,
	"Blue Abishai": -1,
	"Boneclaw": -1,
	"Bronze Scout": -1,
	"Bulezau": -1,
	"Cadaver Collector": -1,
	"Canoloth": -1,
	"Choker": -1,
	"Corpse Flower": -1,
	"Deathlock": -1,
	"Deathlock Mastermind": -1,
	"Deathlock Wight": -1,
	"Demogorgon": -1,
	"Derro": -1,
	"Derro Savant": -1,
	"Dhergoloth": -1,
	"Dire Troll": -1,
	"Drow Arachnomancer": -1,
	"Drow Favored Consort": -1,
	"Drow House Captain": -1,
	"Drow Inquisitor": -1,
	"Drow Matron Mother": -1,
	"Drow Shadowblade": -1,
	"Duergar Despot": -1,
	"Duergar Hammerer": -1,
	"Duergar Kavalrachni": -1,
	"Duergar Mind Master": -1,
	"Duergar Screamer": -1,
	"Duergar Soulblade": -1,
	"Duergar Stone Guard": -1,
	"Duergar Warlord": -1,
	"Duergar Xarron": -1,
	"Dybbuk": -1,
	"Earth Elemental Myrmidon": -1,
	"Eidolon": -1,
	"Elder Oblex": -1,
	"Elder Tempest": -1,
	"Fire Elemental Myrmidon": -1,
	"Fraz-Urb'luu": -1,
	"Frost Salamander": -1,
	"Geryon": -1,
	"Giff": -1,
	"Githyanki Gish": -1,
	"Githyanki Kith'rak": -1,
	"Githyanki Supreme Commander": -1,
	"Githzerai Anarch": -1,
	"Githzerai Enlightened": -1,
	"Gloom Weaver": -1,
	"Gray Render": -1,
	"Graz'zt": -1,
	"Green Abishai": -1,
	"Hellfire Engine": -1,
	"Howler": -1,
	"Hutijin": -1,
	"Hydroloth": -1,
	"Iron Cobra": -1,
	"Juiblex": -1,
	"Kruthik Hive Lord": -1,
	"Leviathan": -1,
	"Marut": -1,
	"Maurezhi": -1,
	"Meazel": -1,
	"Merregon": -1,
	"Merrenoloth": -1,
	"Moloch": -1,
	"Molydeus": -1,
	"Nabassu": -1,
	"Nagpa": -1,
	"Narzugon": -1,
	"Nightwalker": -1,
	"Nupperibo": -1,
	"Oaken Bolter": -1,
	"Oblex Spawn": -1,
	"Ogre Battering Ram": -1,
	"Ogre Bolt Launcher": -1,
	"Ogre Chain Brute": -1,
	"Ogre Howdah": -1,
	"Oinoloth": -1,
	"Orcus": -1,
	"Orthon": -1,
	"Phoenix": -1,
	"Red Abishai": -1,
	"Retriever": -1,
	"Rot Troll": -1,
	"Rutterkin": -1,
	"Sacred Statue": -1,
	"Shadow Dancer": -1,
	"Sibriex": -1,
	"Skulk": -1,
	"Skull Lord": -1,
	"Soul Monger": -1,
	"Spirit Troll": -1,
	"Spring Eladrin": -1,
	"Star Spawn Grue": -1,
	"Star Spawn Hulk": -1,
	"Star Spawn Larva Mage": -1,
	"Star Spawn Mangler": -1,
	"Star Spawn Seer": -1,
	"Steeder Female": -1,
	"Steeder Male": -1,
	"Steel Predator": -1,
	"Stone Cursed": -1,
	"Stone Defender": -1,
	"Summer Eladrin": -1,
	"Sword Wraith Commander": -1,
	"Sword Wraith Warrior": -1,
	"The Angry": -1,
	"The Hungry": -1,
	"The Lonely": -1,
	"The Lost": -1,
	"The Wretched": -1,
	"Titivilus": -1,
	"Tortle": -1,
	"Tortle Druid": -1,
	"Vampiric Mist": -1,
	"Venom Troll": -1,
	"Wastrilith": -1,
	"Water Elemental Myrmidon": -1,
	"White Abishai": -1,
	"Winter Eladrin": -1,
	"Yagnoloth": -1,
	"Yeenoghu": -1,
	"Young Kruthik": -1,
	"Zaratan": -1,
	"Zariel": -1,
	"Zuggtmoy": -1,
};
var RoD_Dialog = {
	"Awakened Zurkhwood": -1,
	"Baphomet": -1,
	"Bridesmaid of Zuggtmoy": -1,
	"Chamberlain of Zuggtmoy": -1,
	"Chuul Spore Servant": -1,
	"Demogorgon": -1,
	"Derro": -1,
	"Derro Savant": -1,
	"Droki": -1,
	"Drow Spore Servant": -1,
	"Duergar Spore Servant": -1,
	"Duergar Darkhaft": -1,
	"Duergar Kavalrachni": -1,
	"Duergar Keeper of the Flame": -1,
	"Duergar Soulblade": -1,
	"Duergar Stone Guard": -1,
	"Duergar Xarron": -1,
	"Fraz-Urb'luu": -1,
	"Graz'zt": -1,
	"Grisha": -1,
	"Hook Horror Spore Servant": -1,
	"Ixitxachitl": -1,
	"Ixitxachitl Cleric": -1,
	"Juiblex": -1,
	"Narrak": -1,
	"Orcus": -1,
	"Steeder (Female)": -1,
	"Steeder (Male)": -1,
	"The Pudding King": -1,
	"Troglodyte Champion of Laogzed": -1,
	"Vampiric Ixitxachitl": -1,
	"Vampiric Ixitxachitl Cleric": -1,
	"Yestabrod": -1,
	"Yeenoghu": -1,
	"Zuggtmoy": -1,
};
var SKT_Dialog = {
	"Augrek Brighthelm": -1,
	"Beldora": -1,
	"Crag Cat": -1,
	"Darathra Shendrel": -1,
	"Darz Helgar": -1,
	"Duvessa Shane": -1,
	"Ghelryn Foehammer": -1,
	"Hulking Crab": -1,
	"Iymrith, Ancient Blue Dragon": -1,
	"Lifferlas": -1,
	"Maegera the Dawn Titan": -1,
	"Markham Southwell": -1,
	"Miros Xelbrin": -1,
	"Narth Tezrin": -1,
	"Naxene Drathkala": -1,
	"Nimir": -1,
	"Oren Yogilvy": -1,
	"Orlekto": -1,
	"Othovir": -1,
	"Purple Wormling": -1,
	"Shaldoor": -1,
	"Sir Baric Nylef": -1,
	"Sirac of Suzail": -1,
	"Shalvus Martholio": -1,
	"Tressym": -1,
	"Urgala Meltimer": -1,
	"Uthgardt Shaman": -1,
	"Vaasha": -1,
	"Yakfolk Warrior": -1,
	"Yakfolk Priest": -1,
	"Zi Liang": -1,
};
var TftYP_Dialog = {
	"Animated Table": -1,
	"Barghest": -1,
	"Centaur Mummy": -1,
	"Champion": -1,
	"Deathlock Wight": -1,
	"Dread Warrior": -1,
	"Duergar Spy": -1,
	"Giant Crayfish": -1,
	"Giant Lightning Eel": -1,
	"Giant Subterranean Lizard": -1,
	"Greater Zombie": -1,
	"Kalka-Kylla": -1,
	"Kelpie": -1,
	"Malformed Kraken": -1,
	"Nereid": -1,
	"Ooze Master": -1,
	"Sea Lion": -1,
	"Sharwyn Hucrele": -1,
	"Sir Braford": -1,
	"Siren": -1,
	"Tarul Var": -1,
	"Thayan Warrior": -1,
	"Thorn Slinger": -1,
	"Vampiric Mist": -1,
	"White Maw": -1,
	"Yusdrayl": -1,
};
var ToA_Dialog = {
	"Acererak": -1,
	"Albino Dwarf Spirit Warrior": -1,
	"Albino Dwarf Warrior": -1,
	"Aldani (Lobsterfolk)": -1,
	"Almiraj": -1,
	"Ankylosaurus Zombie": -1,
	"Artus Cimber": -1,
	"Assassin Vine": -1,
	"Atropal": -1,
	"Chwinga": -1,
	"Dragonbait": -1,
	"Eblis": -1,
	"Flying Monkey": -1,
	"Giant Four-Armed Gargoyle": -1,
	"Giant Snapping Turtle": -1,
	"Girallon Zombie": -1,
	"Jaculi": -1,
	"Kamadan": -1,
	"Liara Portyr": -1,
	"Mantrap": -1,
	"Mwaxanaré": -1,
	"Pterafolk": -1,
	"Ras Nsi": -1,
	"Stone Juggernaut": -1,
	"Su-Monster": -1,
	"Tabaxi Hunter": -1,
	"Tabaxi Minstrel": -1,
	"Tri-Flower Frond": -1,
	"Tyrannosaurus Zombie": -1,
	"Volothamp “Volo” Geddarm": -1,
	"Xandala": -1,
	"Yellow Musk Creeper": -1,
	"Yellow Musk Zombie": -1,
	"Zindar": -1,
	"Zorbo": -1,
};
var ToB_Dialog = {
	"Abominable Beauty": -1,
	"Accursed Defiler": -1,
	"Adult Cave Dragon": -1,
	"Adult Flame Dragon": -1,
	"Adult Mithral Dragon": -1,
	"Adult Rime Worm": -1,
	"Adult Sea Dragon": -1,
	"Adult Void Dragon": -1,
	"Adult Wind Dragon": -1,
	"Akyishigal, Demon Lord of Cockroaches": -1,
	"Al-Aeshma Genie": -1,
	"Ala": -1,
	"Alehouse Drake": -1,
	"Algorith": -1,
	"Alquam, Demon Lord of Night": -1,
	"Alseid": -1,
	"Alseid Grovekeeper": -1,
	"Amphiptere": -1,
	"Ancient Flame Dragon": -1,
	"Ancient Mithral Dragon": -1,
	"Ancient Sea Dragon": -1,
	"Ancient Titan": -1,
	"Ancient Void Dragon": -1,
	"Ancient Wind Dragon": -1,
	"Andrenjinyi": -1,
	"Angatra": -1,
	"Angel (Chained)": -1,
	"Angel (Fidele)": -1,
	"Angler Worm": -1,
	"Anubian": -1,
	"Apau Perape": -1,
	"Arbeyach": -1,
	"Arboreal Grappler": -1,
	"Arcane Guardian": -1,
	"Aridni": -1,
	"Asanbosam": -1,
	"Ash Drake": -1,
	"Automata Devil": -1,
	"Avatar of Boreas": -1,
	"Azza Gremlin": -1,
	"Baba Yaga's Horsemen, Black Night": -1,
	"Baba Yaga's Horsemen, Bright Day": -1,
	"Baba Yaga's Horsemen, Red Sun": -1,
	"Bagiennik": -1,
	"Bandit Lord": -1,
	"Bastet Temple Cat": -1,
	"Bear King": -1,
	"Bearfolk": -1,
	"Behtu": -1,
	"Beli": -1,
	"Bereginyas": -1,
	"Berstuc": -1,
	"Black Knight Commander": -1,
	"Blemmyes": -1,
	"Blood Hag": -1,
	"Boloti": -1,
	"Bone Collective": -1,
	"Bone Crab": -1,
	"Bone Swarm": -1,
	"Bouda": -1,
	"Broodiken": -1,
	"Bucca": -1,
	"Bukavac": -1,
	"Buraq": -1,
	"Burrowling": -1,
	"Cactid": -1,
	"Camazotz, Demon Lord of Bats And Fire": -1,
	"Cambium": -1,
	"Carrion Beetle": -1,
	"Cave Dragon Wyrmling": -1,
	"Cavelight Moss": -1,
	"Chelicerae": -1,
	"Chernomoi": -1,
	"Child of The Briar": -1,
	"Chort Devil": -1,
	"Chronalmental": -1,
	"Cikavak": -1,
	"City Watch Captian": -1,
	"Clockwork Abomination": -1,
	"Clockwork Beetle": -1,
	"Clockwork Beetle Swarm": -1,
	"Clockwork Hound": -1,
	"Clockwork Huntsman": -1,
	"Clockwork Myrmidon": -1,
	"Clockwork Watchman": -1,
	"Clockwork Weaving Spider": -1,
	"Clurichaun": -1,
	"Cobbleswarm": -1,
	"Coral Drake": -1,
	"Corpse Mound": -1,
	"Corrupting Ooze": -1,
	"Crimson Drake": -1,
	"Crystalline Devil": -1,
	"Dau": -1,
	"Death Butterfly Swarm": -1,
	"Deathcap Myconid": -1,
	"Deathwisp": -1,
	"Deep Drake": -1,
	"Deep One": -1,
	"Deep One Archimandrite": -1,
	"Deep One Hybrid Priest": -1,
	"Degenerate Titan": -1,
	"Derro Fetal Savant": -1,
	"Derro Shadow Antipaladin": -1,
	"Desert Giant": -1,
	"Devilbound Gnomish Prince": -1,
	"Dipsa": -1,
	"Dissimortuum": -1,
	"Dogmole": -1,
	"Dogmole Juggernaut": -1,
	"Domovoi": -1,
	"Doppelrat": -1,
	"Dorreq": -1,
	"Dragon Eel": -1,
	"Dragonleaf Tree": -1,
	"Drakon": -1,
	"Dream Eater": -1,
	"Drowned Maiden": -1,
	"Dullahan": -1,
	"Dune Mimic": -1,
	"Duskthorn Dryad": -1,
	"Dust Goblin": -1,
	"Dwarven Ringmage": -1,
	"Eala": -1,
	"Eater of Dust (Yakat-Shi)": -1,
	"Edimmu": -1,
	"Eel Hound": -1,
	"Einherjar": -1,
	"Elder Shadow Drake": -1,
	"Eleinomae": -1,
	"Elemental Locus": -1,
	"Elvish Veteran Archer": -1,
	"Emerald Eye": -1,
	"Emerald Order Cult Leader": -1,
	"Emperor of The Ghouls": -1,
	"Empty Cloak": -1,
	"Eonic Drifter": -1,
	"Erina Defender": -1,
	"Erina Scrounger": -1,
	"Eye Golem": -1,
	"Far Darrig": -1,
	"Fate Eater": -1,
	"Fear Smith (Fiarsídhe)": -1,
	"Fellforged": -1,
	"Fext": -1,
	"Feyward Tree": -1,
	"Fire Dancer Swarm": -1,
	"Firebird": -1,
	"Firegeist": -1,
	"Flab Giant": -1,
	"Flame Dragon Wyrmling": -1,
	"Flutterflesh": -1,
	"Folk of Leng": -1,
	"Forest Marauder": -1,
	"Fraughashar": -1,
	"Frostveil": -1,
	"Garroter Crab": -1,
	"Gbahali (Postosuchus)": -1,
	"Gearforged Templar": -1,
	"Gerridae": -1,
	"Ghost Knight": -1,
	"Ghostwalk Spider": -1,
	"Ghoul (Beggar)": -1,
	"Ghoul (Bonepowder)": -1,
	"Ghoul (Darakhul)": -1,
	"Ghoul (Imperial)": -1,
	"Ghoul (Iron)": -1,
	"Giant Ant": -1,
	"Giant Ant Queen": -1,
	"Gilded Devil": -1,
	"Glass Gator": -1,
	"Gnarljak": -1,
	"Gnoll Havoc Runner": -1,
	"Goat-Man": -1,
	"Gray Thirster": -1,
	"Greater Death Butterfly Swarm": -1,
	"Grim Jester": -1,
	"Gug": -1,
	"Gypsosphinx": -1,
	"Haugbui": -1,
	"Herald of Blood": -1,
	"Herald of Darkness": -1,
	"Hoard Golem": -1,
	"Horakh": -1,
	"Hound of The Night": -1,
	"Hraesvelgr The Corpse Swallower": -1,
	"Hulking Whelp": -1,
	"Hundun": -1,
	"Ia'affrat": -1,
	"Ice Maiden": -1,
	"Idolic Deity": -1,
	"Imy-Ut Ushabti": -1,
	"Ink Devil": -1,
	"Isonade": -1,
	"J'ba Fofi Spider": -1,
	"Jaculus": -1,
	"Jotun Giant": -1,
	"Kalke": -1,
	"Kikimora": -1,
	"Kishi": -1,
	"Kobold Alchemist": -1,
	"Kobold Chieftain": -1,
	"Kobold Trapsmith": -1,
	"Kongamato": -1,
	"Koralk (Harvester Devil)": -1,
	"Koschei": -1,
	"Kot Bayun": -1,
	"Krake Spawn": -1,
	"Lake Troll": -1,
	"Lantern Dragonette": -1,
	"Lemurfolk (Kaguani)": -1,
	"Lemurfolk Greyfur": -1,
	"Leshy": -1,
	"Library Automaton": -1,
	"Lich Hound": -1,
	"Likho": -1,
	"Lindwurm": -1,
	"Liosalfar": -1,
	"Living Wick": -1,
	"Lord of The Hunt": -1,
	"Lorelei": -1,
	"Loxoda": -1,
	"Lunar Devil": -1,
	"Mahoru": -1,
	"Malakbel": -1,
	"Mallqui": -1,
	"Malphas (Storm Crow)": -1,
	"Mammon": -1,
	"Mamura": -1,
	"Manabane Scarab Swarm": -1,
	"Map Mimic": -1,
	"Mask Wight": -1,
	"Mavka": -1,
	"Mbielu": -1,
	"Mechuiti, Demon Lord of Apes": -1,
	"Mirror Hag": -1,
	"Mi-Go": -1,
	"Millitaur": -1,
	"Mindrot Thrall": -1,
	"Mirager": -1,
	"Miremal": -1,
	"Mngwa": -1,
	"Monolith Champion": -1,
	"Monolith Footman": -1,
	"Moonlit King": -1,
	"Mordant Snare": -1,
	"Morphoi": -1,
	"Moss Lurker": -1,
	"Myling": -1,
	"Naina": -1,
	"Ngobou": -1,
	"Nichny": -1,
	"Night Scorpion": -1,
	"Nightgarm": -1,
	"Nihilethic Zombie": -1,
	"Nkosi": -1,
	"Nkosi Pridelord": -1,
	"Nkosi War Ostrich": -1,
	"Noctiny": -1,
	"Oculo Swarm": -1,
	"Ogre Chieftain, Corrupted": -1,
	"Oozasis": -1,
	"Orobas Devil": -1,
	"Ostinato": -1,
	"Owl Harpy": -1,
	"Paper Drake": -1,
	"Pombero": -1,
	"Possessed Pillar": -1,
	"Prismatic Beetle Swarm": -1,
	"Psoglav Demon": -1,
	"Putrid Haunt": -1,
	"Qorgeth, Demon Lord of The Devouring Worm": -1,
	"Queen of Night And Magic": -1,
	"Queen of Witches": -1,
	"Qwyllion": -1,
	"Ramag": -1,
	"Rat King": -1,
	"Ratatosk": -1,
	"Ratfolk": -1,
	"Ratfolk Rogue": -1,
	"Ravenala": -1,
	"Ravenfolk Doom Croaker": -1,
	"Ravenfolk Scout": -1,
	"Ravenfolk Warrior": -1,
	"Red Hag": -1,
	"Red-Banded Line Spider": -1,
	"Redcap": -1,
	"Rift Swine": -1,
	"Rime Worm Grub": -1,
	"Risen Reaver": -1,
	"River King": -1,
	"Roachling Lord": -1,
	"Roachling Skirmisher": -1,
	"Rotting Wind": -1,
	"Rubezahl": -1,
	"Rum Gremlin": -1,
	"Rusalka": -1,
	"Rust Drake": -1,
	"Spawn of Akyishigal": -1,
	"Skin Bat": -1,
	"Spawn of Arbeyach": -1,
	"Salt Devil": -1,
	"Salt Golem": -1,
	"Sand Hag": -1,
	"Sand Silhouette": -1,
	"Sand Spider": -1,
	"Sandman": -1,
	"Sandwyrm": -1,
	"Sap Demon": -1,
	"Sarcophagus Slime": -1,
	"Sathaq Worm": -1,
	"Savager": -1,
	"Scheznyki": -1,
	"Scorpion Cultist": -1,
	"Sea Dragon Wyrmling": -1,
	"Selang": -1,
	"Serpopard": -1,
	"Shabti": -1,
	"Shadhavar": -1,
	"Shadow Beast": -1,
	"Spinosaurus": -1,
	"Star Drake": -1,
	"Shadow Fey": -1,
	"Shadow Fey Duelist": -1,
	"Shadow Fey Enchantress": -1,
	"Shadow Fey Forest Hunter": -1,
	"Shadow Fey Guardian": -1,
	"Snow Queen": -1,
	"Smaragdine Golem": -1,
	"Steam Golem": -1,
	"Stygian Fat-Tailed Scorpion": -1,
	"Shellycoat": -1,
	"Shoggoth": -1,
	"Shroud": -1,
	"Skein Witch": -1,
	"Sharkjaw Skeleton": -1,
	"Skitterhaunt": -1,
	"Slow Storm": -1,
	"Swamp Adder": -1,
	"Son of Fenris": -1,
	"Soul Eater": -1,
	"Spark": -1,
	"Spectral Guardian": -1,
	"Spider of Leng": -1,
	"Spider Thief": -1,
	"Spire Walker": -1,
	"Star Spawn of Cthulhu": -1,
	"Stryx": -1,
	"Stuhac": -1,
	"Subek": -1,
	"Suturefly": -1,
	"Sluagh Swarm": -1,
	"Totivillus, Scribe of Hell": -1,
	"Thursir Giant": -1,
	"Temple Dog": -1,
	"Thuellai": -1,
	"Titanoboa": -1,
	"Tophet": -1,
	"Tosculi Drone": -1,
	"Tosculi Elite Bow Raider": -1,
	"Tosculi Hive-Queen": -1,
	"Tosculi Warrior": -1,
	"Treacle": -1,
	"Trollkin Reaver": -1,
	"Tusked Skyfish": -1,
	"Uraeus": -1,
	"Urochar (Strangling Watcher)": -1,
	"Ushabti": -1,
	"Umbral Vampire": -1,
	"Venomous Mummy": -1,
	"Vine Troll Skeleton": -1,
	"Vaettir": -1,
	"Valkyrie": -1,
	"Vapor Lynx": -1,
	"Vesiculosa": -1,
	"Vila": -1,
	"Vile Barber": -1,
	"Vine Lord": -1,
	"Vine Lord's Tendril Puppet": -1,
	"Voidling": -1,
	"Vampire Warlock-Variant": -1,
	"Wyrmling Wind Dragon": -1,
	"Wolf Spirit Swarm": -1,
	"Weeping Treant": -1,
	"Wampus Cat": -1,
	"Water Leaper": -1,
	"Wharfling": -1,
	"Wharfling Swarm": -1,
	"White Ape": -1,
	"Witchlight": -1,
	"Wormhearted Suffragan": -1,
	"Wolf Reaver Dwarf": -1,
	"Xanka": -1,
	"Xhkarsh": -1,
	"Young Spinosaurus": -1,
	"Young Cave Dragon": -1,
	"Young Flame Dragon": -1,
	"Young Mithral Dragon": -1,
	"Young Sea Dragon": -1,
	"Young Void Dragon": -1,
	"Void Dragon Wyrmling": -1,
	"Young Wind Dragon": -1,
	"Ychen Bannog": -1,
	"Zanskaran Viper": -1,
	"Zaratan": -1,
	"Zimwi": -1,
	"Zmey": -1,
	"Zmey Headling": -1,
};
var ToD_Dialog = {
	"Ambush Drake": -1,
	"Azbara Jos": -1,
	"Blagothkus": -1,
	"Captain Othelstan": -1,
	"Dragonclaw": -1,
	"Dragonfang": -1,
	"Dragonsoul": -1,
	"Dragonwing": -1,
	"Dralmorrer Borngray": -1,
	"Frulam Mondath": -1,
	"Guard Drake": -1,
	"Ice Toad": -1,
	"Jamna Gleamsilver": -1,
	"Langdedrosa Cyanwrath": -1,
	"Naergoth Bladelord": -1,
	"Neronvain": -1,
	"Pharblex Spattergoo": -1,
	"Rath Modar": -1,
	"Rezmir": -1,
	"Severin": -1,
	"Talis the White": -1,
	"Thurl Merosska": -1,
	"Tiamat": -1,
};
var Tortle_Dialog = {
	"Decapus": -1,
	"Geonid": -1,
	"Marine Decapus": -1,
	"Topi": -1,
	"Tortle": -1,
	"Tortle Druid": -1,
};
var VGtM_Dialog = {
	"Abjurer": -1,
	"Alhoon": -1,
	"Annis Hag": -1,
	"Annis Hag (Death Coven)": -1,
	"Annis Hag (Nature Coven)": -1,
	"Annis Hag (Prophecy Coven)": -1,
	"Apprentice Wizard": -1,
	"Archdruid": -1,
	"Archer": -1,
	"Aurochs": -1,
	"Babau": -1,
	"Banderhobb": -1,
	"Bard": -1,
	"Barghest": -1,
	"Bheur Hag": -1,
	"Bheur Hag (Death)": -1,
	"Bheur Hag (Prophecy)": -1,
	"Bheur Hag (Nature)": -1,
	"Black Guard Drake": -1,
	"Blackguard": -1,
	"Blue Guard Drake": -1,
	"Bodak": -1,
	"Boggle": -1,
	"Brontosaurus": -1,
	"Catoblepas": -1,
	"Cave Fisher": -1,
	"Champion": -1,
	"Chitine": -1,
	"Choldrith": -1,
	"Cloud Giant Smiling One": -1,
	"Conjurer": -1,
	"Cow": -1,
	"Cranium Rat": -1,
	"Darkling": -1,
	"Darkling Elder": -1,
	"Death Kiss": -1,
	"Deep Rothé": -1,
	"Deep Scion": -1,
	"Deinonychus": -1,
	"Devourer": -1,
	"Dimetrodon": -1,
	"Diviner": -1,
	"Dolphin": -1,
	"Draegloth": -1,
	"Elder Brain": -1,
	"Enchanter": -1,
	"Evoker": -1,
	"Fire Giant Dreadnought": -1,
	"Firenewt Warlock of Imix": -1,
	"Firenewt Warrior": -1,
	"Flail Snail": -1,
	"Flind": -1,
	"Froghemoth": -1,
	"Frost Giant Everlasting One": -1,
	"Gauth": -1,
	"Gazer": -1,
	"Giant Strider": -1,
	"Girallon": -1,
	"Gnoll Flesh Gnawer": -1,
	"Gnoll Hunter": -1,
	"Gnoll Witherling": -1,
	"Green Guard Drake": -1,
	"Grung": -1,
	"Grung Elite Warrior": -1,
	"Grung Wildling": -1,
	"Guard Drake": -1,
	"Hadrosaurus": -1,
	"Hobgoblin Devastator": -1,
	"Hobgoblin Iron Shadow": -1,
	"Illithilich": -1,
	"Illusionist": -1,
	"Ki-rin": -1,
	"Kobold Dragonshield": -1,
	"Kobold Inventor": -1,
	"Kobold Scale Sorcerer": -1,
	"Korred": -1,
	"Kraken Priest": -1,
	"Leucrotta": -1,
	"Martial Arts Adept": -1,
	"Master Thief": -1,
	"Maw Demon": -1,
	"Meenlock": -1,
	"Mind Flayer Psion": -1,
	"Mindwitness": -1,
	"Morkoth": -1,
	"Mouth of Grolantor": -1,
	"Necromancer": -1,
	"Neogi": -1,
	"Neogi Hatchling": -1,
	"Neogi Master": -1,
	"Neothelid": -1,
	"Nilbog": -1,
	"Orc Blade of Ilneval": -1,
	"Orc Claw of Luthic": -1,
	"Orc Hand of Yurtrus": -1,
	"Orc Nurtured One of Yurtrus": -1,
	"Orc Red Fang of Shargaas": -1,
	"Ox": -1,
	"Quetzalcoatlus": -1,
	"Quickling": -1,
	"Red Guard Drake": -1,
	"Redcap": -1,
	"Rothé": -1,
	"Sea Spawn": -1,
	"Shadow Mastiff": -1,
	"Shoosuva": -1,
	"Slithering Tracker": -1,
	"Spawn of Kyuss": -1,
	"Stegosaurus": -1,
	"Stench Kow": -1,
	"Stone Giant Dreamwalker": -1,
	"Storm Giant Quintessent": -1,
	"Swarm of Cranium Rats": -1,
	"Swarm of Rot Grubs": -1,
	"Swashbuckler": -1,
	"Tanarukk": -1,
	"Thorny": -1,
	"Tlincalli": -1,
	"Transmuter": -1,
	"Trapper": -1,
	"Ulitharid": -1,
	"Vargouille": -1,
	"Vegepygmy": -1,
	"Vegepygmy Chief": -1,
	"Velociraptor": -1,
	"War Priest": -1,
	"Warlock of the Archfey": -1,
	"Warlock of the Fiend": -1,
	"Warlock of the Great Old One": -1,
	"Warlord": -1,
	"White Guard Drake": -1,
	"Wood Woad": -1,
	"Xvart": -1,
	"Xvart Speaker": -1,
	"Xvart Warlock of Raxivort": -1,
	"Yeth Hound": -1,
	"Yuan-ti Anathema": -1,
	"Yuan-ti Broodguard": -1,
	"Yuan-ti Mind Whisperer": -1,
	"Yuan-ti Nightmare Speaker": -1,
	"Yuan-ti Pit Master": -1,
};

