"Jaggi": {
	name: "Jaggi",
	source: ["Monster Hunter Monster Manual", 4],
	size: "Medium",
	type: "beast (theropod)",
	alignment: "Unaligned",
	ac: [11, "Natural Armor", false],
	hp: 26,
	hd: [4, 8],
	speed: "30 ft",
	scores: [15, 13, 14, 2, 8, 5],
	saves: ["", "", "", "", "", ""],
	skills: "",
	passivePerception: "9",
	languages: "",
	challengeRating: "1/2",
	senses: "",
	damage_resistances: "",
	damage_immunities: "",
	condition_immunities: "",
	damage_vulnerabilities: "",
	attacks: [{
			name: "Bite",
			ability: 1,
			damage: [1, 6, "piercing"],
			range: "Melee (5 ft)",
			description: "",
		}, {
			name: "Claw",
			ability: 1,
			damage: [2, 4, "slashing"],
			range: "Melee (5 ft)",
			description: "",
		},
	],
	traits: [{
			name: "Pack Tactics",
			description: "The Jaggi has advantage on attack rolls against a creature if at least one of the Jaggi's allies is within 5 feet of the creature and the ally isn't incapacitated.",
		},
	],
},
"Jaggia": {
	name: "Jaggia",
	source: ["" "", 6],
	size: "Medium",
	type: "beast (theropod)",
	alignment: "Unaligned",
	ac: [12, "Natural Armor", false],
	hp: 37,
	hd: [5, 8],
	speed: "30 ft",
	scores: [16, 13, 16, 2, 10, 5],
	saves: ["", "", "", "", "", ""],
	skills: "",
	passivePerception: "10",
	languages: "",
	challengeRating: "1",
	senses: "",
	damage_resistances: "",
	damage_immunities: "",
	condition_immunities: "",
	damage_vulnerabilities: "",
	attacks: [{
			name: "Bite",
			ability: 1,
			damage: [2, 8, "piercing"],
			range: "Melee (5 ft)",
			description: "",
		}, {
			name: "Slam",
			ability: 1,
			damage: [2, 6, "bludgeoning"],
			range: "Melee (5 ft)",
			description: "If the target is a creature, it must succeed on a DC 11 Strength saving throw or be knocked prone.",
		},
	],
	traits: [{
			name: "Pack Tactics",
			description: "The Jaggia has advantage on attack rolls against a creature if at least one of the Jaggia's allies is within 5 feet of the creature and the ally isn't incapacitated.",
		}, {
			name: "Brute",
			description: "A melee weapon deals one extra die of its damage when the Jaggia hits with it (included in the attack).",
		},
	],
},
"Great Jaggia": {
	name: "Great Jaggia",
	source: ["", 6],
	size: "Large",
	type: "beast (theropod)",
	alignment: "Unaligned",
	ac: [13, "Natural Armor", false],
	hp: 59,
	hd: [7, 10],
	speed: "30 ft",
	scores: [17, 13, 16, 2, 10, 5],
	saves: ["", "", "", "", "", ""],
	skills: "Athletics +4",
	passivePerception: "10",
	languages: "",
	challengeRating: "2",
	senses: "",
	damage_resistances: "",
	damage_immunities: "",
	condition_immunities: "",
	damage_vulnerabilities: "",
	attacks: [{
			name: "Bite",
			ability: 1,
			damage: [3, 8, "piercing"],
			range: "Melee (5 ft)",
			description: "",
		}, {
			name: "Slam",
			ability: 1,
			damage: [3, 6, "bludgeoning"],
			range: "Melee (5 ft)",
			description: "If the target is a creature, it must succeed on a DC 13 Strength saving throw or be knocked prone.",
		},
	],
	actions: [{
			name: "Alpha Call (1/day)",
			description: "The Great Jaggi calls out for help and 1d4 jaggi and 1d2 Jaggia appears to assist it.",
		},
	],
	traits: [{
			name: "Brute",
			description: "A melee weapon attack deals one extra die of its damage when the Great Jaggi hits with it (included in the attack).",
		}, {
			name: "Pounce",
			description: "If the Great Jaggi moves at least 20 feet. straight toward a creature and then hits it with a slam Attack on the same turn, that target must succeed on a DC 13 Strength saving throw or be knocked prone. If the target is prone, the Great Jaggi can make one bite Attack against it as a Bonus Action.",
		},
	],
},
